//! This file was generated by `parameter_generation.sage`.
//! Prime modulus: 5*2^248 - 1.
use crate::algebra::field::FftField;
use ark_ff::{Fp2Config, Fp256, MontBackend, MontFp, fp2};

#[derive(ark_ff::MontConfig)]
#[modulus = "2261564242916331941866620800950935700259179388000792266395655937654553313279"]
#[generator = "3"]
pub struct FpConfig251;

pub type Fp251 = Fp256<MontBackend<FpConfig251, 4>>;

pub struct Fp2Config251;
impl Fp2Config for Fp2Config251 {
    type Fp = Fp251;
    const NONRESIDUE: Self::Fp =
        MontFp!("2261564242916331941866620800950935700259179388000792266395655937654553313278");
    const FROBENIUS_COEFF_FP2_C1: &'static [Self::Fp] = &[
        MontFp!("1"),
        MontFp!("2261564242916331941866620800950935700259179388000792266395655937654553313278"),
    ];
}
pub type Fp2251 = fp2::Fp2<Fp2Config251>;
impl FftField for Fp2251 {
    const TWO_ADICITY: u32 = 249;
    const TWO_ADIC_ROOT_OF_UNITY: Self = Self {
        c0: MontFp!("1205025138543176579400216426469194982307642063028969157762157265575227047065"),
        c1: MontFp!("1016267646470308916753499664310755376375900607926030331828540496222603030995"),
    };
}
