

# This file was *autogenerated* from the file ./scripts/parameter_generation.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_64 = Integer(64); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_372 = Integer(372); _sage_const_239 = Integer(239)#!/usr/bin/env sage -python

from sage.all import *

def generate_ark_ff_params(p):
    assert p % _sage_const_4  == _sage_const_3 
    bitlen = ceil(log(p, _sage_const_2 ))

    #Number of limbs, Fp
    N = ceil(bitlen / _sage_const_64 )

    #Multiplicative generator of Fp
    Fp = GF(p)
    generator = Fp.multiplicative_generator()    
    # Fp2.<i> = GF(p**2, modulus=x^2+1)

    #Non residue used to extend Fp to Fp2. 3 mod 4 means -1 is a non residue
    nonresidue = Fp(-_sage_const_1 )
    # Action of Frobenius on real part. This is always trivial
    frobenius_coeff_fp2_c1_0 = nonresidue**_sage_const_0 
    # Action of Frobenius on imaginary part. This is -1 for p = 3 mod 4
    frobenius_coeff_fp2_c1_1 = nonresidue**((p-_sage_const_1 )/_sage_const_2 )
    return bitlen, p, N, int(generator),int(nonresidue), int(frobenius_coeff_fp2_c1_0), int(frobenius_coeff_fp2_c1_1)

def pretty_print_ark_ff(bitlen, p, N, generator, nonresidue, frobenius_coeff_fp2_c1_0, frobenius_coeff_fp2_c1_1, str):
    print("//! This file was generated by `parameter_generation.sage`.")
    print("//! Prime modulus: {}.".format(str))
    print("use crate::algebra::field::FftField;")
    print("use ark_ff::{{fp2, Fp2Config, MontBackend, Fp{}, MontFp}};".format(N * _sage_const_64 ))
    print()
    print("#[derive(ark_ff::MontConfig)]")
    print("#[modulus = \"{}\"]".format(p))
    print("#[generator = \"{}\"]".format(generator))
    print("pub struct FpConfig{};".format(bitlen))
    print("\n")
    print("pub type Fp{} = Fp{}<MontBackend<FpConfig{}, {}>>;".format(bitlen, N*_sage_const_64 , bitlen, N))
    print("\n")
    print("pub struct Fp2Config{};".format(bitlen))
    print("impl Fp2Config for Fp2Config{} {{".format(bitlen))
    print("    type Fp = Fp{};".format(bitlen))
    print("    const NONRESIDUE: Self::Fp = MontFp!(\"{}\");".format(nonresidue))
    print("    const FROBENIUS_COEFF_FP2_C1: &'static [Self::Fp] = &[")

    print("    MontFp!(\"{}\"),".format(frobenius_coeff_fp2_c1_0))

    print("    MontFp!(\"{}\"),".format(frobenius_coeff_fp2_c1_1))
    print("];")
    print("}")

def pretty_print_ark_ff_fp2(bitlen, two_adicity, root_of_unity):
    print("pub type Fp2{} = fp2::Fp2<Fp2Config{}>;".format(bitlen, bitlen))
    print("impl FftField for Fp2{} {{".format(bitlen))
    print("\tconst TWO_ADICITY: u32 = {};".format(two_adicity))
    print("\tconst TWO_ADIC_ROOT_OF_UNITY: Self = Self {")
    print("\t\tc0: MontFp!(\"{}\"),".format(root_of_unity.polynomial().list()[_sage_const_0 ]))
    print("\t\tc1: MontFp!(\"{}\"),".format(root_of_unity.polynomial().list()[_sage_const_1 ]))
    print("\t};")
    print("}")

def generate_ark_fp2_params(prime):
    #uses twice the number of bits for an element
    bitlen = ceil(log(prime,_sage_const_2 ))

    # Compute multiplicative subgroup size = t * 2^s. Start by setting s = 0.
    t = (prime**_sage_const_2  - _sage_const_1 )
    two_adicity = _sage_const_0 
    while (t % _sage_const_2  == _sage_const_0 ):
        t /= _sage_const_2 
        two_adicity += _sage_const_1 

    if two_adicity == _sage_const_0 :
        raise BaseException("The prime decomposition doesn't have any factor 2."
            "The 'high 2-adicity' requirement isn't respected")

    if (prime % _sage_const_4 ) == _sage_const_3 :
        F = GF(prime**_sage_const_2 , modulus=x**_sage_const_2 +_sage_const_1 , names=('i',)); (i,) = F._first_ngens(1)
    elif (prime % _sage_const_4 ) == _sage_const_1 :
        F = GF(prime**_sage_const_2 , modulus=x**_sage_const_2 +x-_sage_const_1 , names=('i',)); (i,) = F._first_ngens(1)
    else:
        raise "Prime is not 1 or 3 mod 4"

    multiplicative_gen = F.multiplicative_generator()

    #Calculate the maximal 2-th power root of unity
    root_of_unity = pow(multiplicative_gen, t, prime)

    return bitlen, two_adicity, root_of_unity

PRIME_MODULUS_1 = _sage_const_2 **_sage_const_372 *_sage_const_3 **_sage_const_239  - _sage_const_1 
PRIME_MODULUS_STRING = "2^372*3^239 - 1"
pretty_print_ark_ff(*generate_ark_ff_params(PRIME_MODULUS_1), PRIME_MODULUS_STRING)
pretty_print_ark_ff_fp2(*generate_ark_fp2_params(PRIME_MODULUS_1))

